/* ══════════════════════════════════════════════════════════════════════════════════
   AMERICAS BEST HOME SOLUTIONS — ALL YOUR HOMES LIVE IN THIS ONE FILE
   ▼▼▼ This is the ONLY file you edit to add, change, or remove a home. ▼▼▼

   TO ADD A HOME: copy one { ... } block in the HOMES list below (from its
   opening { to its closing },), paste it after the last one, and change the
   values. Give it a unique "id" — that becomes its web address, e.g.
   id: "memphis-1"  →  home.html?home=memphis-1

   TO MARK A HOME PENDING: change its  status  to "Pending".
   TO REMOVE A HOME: delete its whole { ... } block.
   ═══════════════════════════════════════════════════════════════════════════════════ */

/* --- who to contact — set ONCE, used by every home's page --- */
const CONTACT = {
  phone: "5515509906",                 // digits only, no spaces or dashes — Quo business number
  contactName: "Americas Best Home Solutions",   // used in the text-message greeting
  formspreeId: "xzdlakbq",             // Formspree form code (emails you each lead)
  makeWebhook: "https://hook.us2.make.com/h9jsckkipxxm4ngezfzldtflx4y2efo9",  // Make.com webhook → saves lead to Notion CRM
};

/* --- the homes (155 live, imported from master sheet — published 2026-07-04) --- */
const HOMES = [
  {
    id: "birmingham-al-208-carol",
    city:  "Birmingham",
    state: "AL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 887,
    moveIn:         4000,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "birmingham-al-519-avenue",
    city:  "Birmingham",
    state: "AL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 795,
    moveIn:         2000,
    lockedPrice:    79000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "alton-il-3024-glenwood",
    city:  "Alton",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 525,
    moveIn:         1000,
    lockedPrice:    49000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "bartonville-il-5817-adams",
    city:  "Bartonville",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 975,
    moveIn:         3000,
    lockedPrice:    75000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "belleville-il-528-belvedere",
    city:  "Belleville",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 825,
    moveIn:         2000,
    lockedPrice:    73000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "bethalto-il-319-corbin",
    city:  "Bethalto",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 895,
    moveIn:         2500,
    lockedPrice:    99000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "cahokia-il-500-saint",
    city:  "Cahokia",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 850,
    moveIn:         2000,
    lockedPrice:    79000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "carbondale-il-615-almond",
    city:  "Carbondale",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  900,
    status: "Available",

    monthlyPayment: 925,
    moveIn:         2500,
    lockedPrice:    82500,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "centralia-il-227-hickory",
    city:  "Centralia",
    state: "IL",
    beds:  5,
    baths: 3,
    sqft:  1450,
    status: "Available",

    monthlyPayment: 1025,
    moveIn:         2500,
    lockedPrice:    95000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "centralia-il-805-hickory",
    city:  "Centralia",
    state: "IL",
    beds:  3,
    baths: 2,
    sqft:  "",
    status: "Available",

    monthlyPayment: 795,
    moveIn:         3000,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1035-elmurst",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 865,
    moveIn:         2500,
    lockedPrice:    84000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1073-packard",
    city:  "Decatur",
    state: "IL",
    beds:  3,
    baths: 2,
    sqft:  "",
    status: "Available",

    monthlyPayment: 995,
    moveIn:         2500,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1103-prairie",
    city:  "Decatur",
    state: "IL",
    beds:  4,
    baths: 2,
    sqft:  "",
    status: "Available",

    monthlyPayment: 675,
    moveIn:         2000,
    lockedPrice:    59000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1105-jasper",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 950,
    moveIn:         3000,
    lockedPrice:    84998,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1112-garfield",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 850,
    moveIn:         2000,
    lockedPrice:    76712,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1258-division",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 850,
    moveIn:         3000,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1259-whitmer",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 800,
    moveIn:         1000,
    lockedPrice:    69680,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1263-green",
    city:  "Decatur",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 995,
    moveIn:         3000,
    lockedPrice:    110500,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1286-vanderhoof",
    city:  "Decatur",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 895,
    moveIn:         2500,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1303-whitmer",
    city:  "Decatur",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 850,
    moveIn:         1500,
    lockedPrice:    73867.45,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-132-23rd",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 875,
    moveIn:         2000,
    lockedPrice:    77710,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1329-riverside",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 950,
    moveIn:         3000,
    lockedPrice:    88926.66,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1344-condit",
    city:  "Decatur",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 870,
    moveIn:         3000,
    lockedPrice:    83000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1365-walnut",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 865,
    moveIn:         1800,
    lockedPrice:    79995,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1455-whitmer",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 865,
    moveIn:         2250,
    lockedPrice:    87000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1505-walnut",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 750,
    moveIn:         1500,
    lockedPrice:    75000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1553-hickory",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 875,
    moveIn:         2000,
    lockedPrice:    77000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1652-hickory",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 825,
    moveIn:         2000,
    lockedPrice:    82000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1700-grand",
    city:  "Decatur",
    state: "IL",
    beds:  1,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 625,
    moveIn:         1000,
    lockedPrice:    57900,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1729-woodford",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 775,
    moveIn:         2000,
    lockedPrice:    73000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1755-monroe",
    city:  "Decatur",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 800,
    moveIn:         2000,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1764-johns",
    city:  "Decatur",
    state: "IL",
    beds:  1,
    baths: 1.5,
    sqft:  "",
    status: "Available",

    monthlyPayment: 775,
    moveIn:         2000,
    lockedPrice:    85000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1818-clay",
    city:  "Decatur",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 900,
    moveIn:         2500,
    lockedPrice:    99500,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1830-lowber",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 2,
    sqft:  864,
    status: "Available",

    monthlyPayment: 900,
    moveIn:         1700,
    lockedPrice:    78280,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1908-union",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 799,
    moveIn:         3000,
    lockedPrice:    79000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-1975-st",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 2,
    sqft:  "",
    status: "Available",

    monthlyPayment: 1200,
    moveIn:         3000,
    lockedPrice:    119000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-2061-college",
    city:  "Decatur",
    state: "IL",
    beds:  3,
    baths: 2,
    sqft:  "",
    status: "Available",

    monthlyPayment: 1300,
    moveIn:         3500,
    lockedPrice:    119000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-2148-church",
    city:  "Decatur",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  936,
    status: "Available",

    monthlyPayment: 1050,
    moveIn:         3000,
    lockedPrice:    95500,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-238-peoria",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 825,
    moveIn:         2500,
    lockedPrice:    83500,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-2448-wood",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 900,
    moveIn:         2500,
    lockedPrice:    102250,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-254-peoria",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 835,
    moveIn:         2000,
    lockedPrice:    82000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-2550-main",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 850,
    moveIn:         2000,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-2618-garfield",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1.5,
    sqft:  "",
    status: "Available",

    monthlyPayment: 630,
    moveIn:         1500,
    lockedPrice:    64999,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-2827-hickory",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 250,
    moveIn:         1000,
    lockedPrice:    15000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-305-maffit",
    city:  "Decatur",
    state: "IL",
    beds:  4,
    baths: 3,
    sqft:  2020,
    status: "Available",

    monthlyPayment: 1295,
    moveIn:         3500,
    lockedPrice:    125000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-327-stuart",
    city:  "Decatur",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 875,
    moveIn:         2000,
    lockedPrice:    89900,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-347-stone",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 845,
    moveIn:         2300,
    lockedPrice:    84000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-415-division",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 2.5,
    sqft:  "",
    status: "Available",

    monthlyPayment: 840,
    moveIn:         3000,
    lockedPrice:    106500,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-450-22nd",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 875,
    moveIn:         3000,
    lockedPrice:    83672.2,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-462-leafland",
    city:  "Decatur",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 975,
    moveIn:         3000,
    lockedPrice:    88500,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-515-boyd",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 825,
    moveIn:         1500,
    lockedPrice:    76542.93,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-722-16th",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 975,
    moveIn:         3000,
    lockedPrice:    99500,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-767-whitmer",
    city:  "Decatur",
    state: "IL",
    beds:  3,
    baths: 1.5,
    sqft:  1170,
    status: "Available",

    monthlyPayment: 925,
    moveIn:         2000,
    lockedPrice:    88000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-780-cushing",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 500,
    moveIn:         2000,
    lockedPrice:    55000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-821-oakland",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 749,
    moveIn:         2000,
    lockedPrice:    78993,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-835-whitmer",
    city:  "Decatur",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 845,
    moveIn:         2000,
    lockedPrice:    79000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-927-street",
    city:  "Decatur",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 900,
    moveIn:         2500,
    lockedPrice:    89995,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "decatur-il-968-view",
    city:  "Decatur",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 950,
    moveIn:         3000,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "eastalton-il-140-illinois",
    city:  "East Alton",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 695,
    moveIn:         2000,
    lockedPrice:    69000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "eastcarondelet-il-2949-adams",
    city:  "East Carondelet",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 695,
    moveIn:         2000,
    lockedPrice:    64995,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "eaststlouis-il-1311-51st",
    city:  "East St. Louis",
    state: "IL",
    beds:  1,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 450,
    moveIn:         0,
    lockedPrice:    45000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "eaststlouis-il-3511-converse",
    city:  "East St. Louis",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 995,
    moveIn:         2000,
    lockedPrice:    83000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "eaststlouis-il-3720-walnut",
    city:  "East St. Louis",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 900,
    moveIn:         2500,
    lockedPrice:    74900,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "eaststlouis-il-5538-avon",
    city:  "East St. Louis",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 890,
    moveIn:         2000,
    lockedPrice:    87000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "eaststlouis-il-5617-warren",
    city:  "East St. Louis",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 790,
    moveIn:         1600,
    lockedPrice:    79000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "eaststlouis-il-563-24th",
    city:  "East St. Louis",
    state: "IL",
    beds:  4,
    baths: 2.5,
    sqft:  "",
    status: "Available",

    monthlyPayment: 850,
    moveIn:         2500,
    lockedPrice:    79000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "eaststlouis-il-59-jarvis",
    city:  "East St. Louis",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 845,
    moveIn:         3000,
    lockedPrice:    99000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "fairfield-il-1200-6th",
    city:  "Fairfield",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 875,
    moveIn:         3000,
    lockedPrice:    75000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "fulton-il-602-18th",
    city:  "Fulton",
    state: "IL",
    beds:  2,
    baths: 1.5,
    sqft:  "",
    status: "Available",

    monthlyPayment: 965,
    moveIn:         2000,
    lockedPrice:    79000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "granitecity-il-2317-grand",
    city:  "Granite City",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 750,
    moveIn:         2000,
    lockedPrice:    79000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "granitecity-il-2512-24th",
    city:  "Granite City",
    state: "IL",
    beds:  1,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 495,
    moveIn:         800,
    lockedPrice:    45000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "harrisburg-il-410-shaw",
    city:  "Harrisburg",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 600,
    moveIn:         1000,
    lockedPrice:    49000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "herrin-il-11-b",
    city:  "Herrin",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 950,
    moveIn:         2500,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "herrin-il-905-monroe",
    city:  "Herrin",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 950,
    moveIn:         3000,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "newathens-il-106-benton",
    city:  "New Athens",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 650,
    moveIn:         1000,
    lockedPrice:    67000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "nokomis-il-304-spruce",
    city:  "Nokomis",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 575,
    moveIn:         1000,
    lockedPrice:    41000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "nokomis-il-416-griffin",
    city:  "Nokomis",
    state: "IL",
    beds:  1,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 675,
    moveIn:         1000,
    lockedPrice:    50000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-1104-smith",
    city:  "Peoria",
    state: "IL",
    beds:  4,
    baths: 2,
    sqft:  "",
    status: "Available",

    monthlyPayment: 490,
    moveIn:         2500,
    lockedPrice:    49000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-1117-glendale",
    city:  "Peoria",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 850,
    moveIn:         2000,
    lockedPrice:    75000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-1220-john",
    city:  "Peoria",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 800,
    moveIn:         2000,
    lockedPrice:    77000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-1610-lydia",
    city:  "Peoria",
    state: "IL",
    beds:  4,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 850,
    moveIn:         2500,
    lockedPrice:    84999,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-1615-arago",
    city:  "Peoria",
    state: "IL",
    beds:  1,
    baths: 1,
    sqft:  592,
    status: "Available",

    monthlyPayment: 695,
    moveIn:         2000,
    lockedPrice:    68000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-1714-livingston",
    city:  "Peoria",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 849.26,
    moveIn:         2500,
    lockedPrice:    86000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-1714-lydia",
    city:  "Peoria",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 195,
    moveIn:         750,
    lockedPrice:    14000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-1715-bourland",
    city:  "Peoria",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 705,
    moveIn:         1750,
    lockedPrice:    79000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-1829-stanley",
    city:  "Peoria",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 795,
    moveIn:         1300,
    lockedPrice:    82000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-2313-wiswall",
    city:  "Peoria",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 750,
    moveIn:         1250,
    lockedPrice:    79000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-2601-latrobe",
    city:  "Peoria",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 195,
    moveIn:         750,
    lockedPrice:    14000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-2710-antoinette",
    city:  "Peoria",
    state: "IL",
    beds:  1,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 225,
    moveIn:         750,
    lockedPrice:    15000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-422-louisa",
    city:  "Peoria",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 515,
    moveIn:         1000,
    lockedPrice:    43000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-609-tracy",
    city:  "Peoria",
    state: "IL",
    beds:  4,
    baths: 2,
    sqft:  1344,
    status: "Available",

    monthlyPayment: 612.88,
    moveIn:         2000,
    lockedPrice:    69000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-715-thrush",
    city:  "Peoria",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  804,
    status: "Available",

    monthlyPayment: 650,
    moveIn:         2000,
    lockedPrice:    59000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-721-matthew",
    city:  "Peoria",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 825,
    moveIn:         3000,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-812-macqueen",
    city:  "Peoria",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 749,
    moveIn:         2500,
    lockedPrice:    79000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "peoria-il-911-hurlburt",
    city:  "Peoria",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 750,
    moveIn:         1500,
    lockedPrice:    70500,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "quincy-il-706-cedar",
    city:  "Quincy",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 505,
    moveIn:         1000,
    lockedPrice:    43000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "sauget-il-1320-williams",
    city:  "Sauget",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  936,
    status: "Available",

    monthlyPayment: 625,
    moveIn:         1500,
    lockedPrice:    49900,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "sauget-il-17-cahokia",
    city:  "Sauget",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  1187,
    status: "Available",

    monthlyPayment: 450,
    moveIn:         1000,
    lockedPrice:    29000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "sauget-il-26-leonard",
    city:  "Sauget",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  936,
    status: "Available",

    monthlyPayment: 875,
    moveIn:         2500,
    lockedPrice:    72000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "sauget-il-306-isabell",
    city:  "Sauget",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  720,
    status: "Available",

    monthlyPayment: 750,
    moveIn:         1500,
    lockedPrice:    59000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "sauget-il-523-saint",
    city:  "Sauget",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  925,
    status: "Available",

    monthlyPayment: 895,
    moveIn:         2500,
    lockedPrice:    76000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "sauget-il-722-saint",
    city:  "Sauget",
    state: "IL",
    beds:  3,
    baths: 1,
    sqft:  896,
    status: "Available",

    monthlyPayment: 925,
    moveIn:         2500,
    lockedPrice:    79000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "sauget-il-8-helen",
    city:  "Sauget",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  720,
    status: "Available",

    monthlyPayment: 795,
    moveIn:         2500,
    lockedPrice:    69000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "springfield-il-2228-brown",
    city:  "Springfield",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 645,
    moveIn:         1000,
    lockedPrice:    65000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "witt-il-529-2nd",
    city:  "Witt",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 675,
    moveIn:         1000,
    lockedPrice:    50000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "woodriver-il-329-park",
    city:  "Wood River",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 850,
    moveIn:         2500,
    lockedPrice:    69000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "woodriver-il-830-wood",
    city:  "Wood River",
    state: "IL",
    beds:  2,
    baths: 1,
    sqft:  1120,
    status: "Available",

    monthlyPayment: 850,
    moveIn:         2000,
    lockedPrice:    79000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "edwardsport-in-108-shipping",
    city:  "Edwardsport",
    state: "IN",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 925,
    moveIn:         3000,
    lockedPrice:    79500,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "muncie-in-319-10th",
    city:  "Muncie",
    state: "IN",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 850,
    moveIn:         2500,
    lockedPrice:    85000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "detroit-mi-13218-greiner",
    city:  "Detroit",
    state: "MI",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 1195,
    moveIn:         2900,
    lockedPrice:    99000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "flint-mi-1101-alvord",
    city:  "Flint",
    state: "MI",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 845,
    moveIn:         2000,
    lockedPrice:    76000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "flint-mi-1218-pinehurst",
    city:  "Flint",
    state: "MI",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 795,
    moveIn:         2000,
    lockedPrice:    64000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "flint-mi-1802-woodlin",
    city:  "Flint",
    state: "MI",
    beds:  2,
    baths: 1,
    sqft:  947,
    status: "Available",

    monthlyPayment: 875,
    moveIn:         3000,
    lockedPrice:    90000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "flint-mi-2023-cadillac",
    city:  "Flint",
    state: "MI",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 925,
    moveIn:         2500,
    lockedPrice:    89900,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "flint-mi-2433-pennsylvania",
    city:  "Flint",
    state: "MI",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 825,
    moveIn:         2500,
    lockedPrice:    85000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "flint-mi-246-york",
    city:  "Flint",
    state: "MI",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 795,
    moveIn:         1800,
    lockedPrice:    67000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "flint-mi-2621-churchhill",
    city:  "Flint",
    state: "MI",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 745,
    moveIn:         2000,
    lockedPrice:    69500,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "flint-mi-345-baltimore",
    city:  "Flint",
    state: "MI",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 875,
    moveIn:         3000,
    lockedPrice:    84900,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "flint-mi-3501-milbourne",
    city:  "Flint",
    state: "MI",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 775,
    moveIn:         2200,
    lockedPrice:    77200,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "flint-mi-3618-branch",
    city:  "Flint",
    state: "MI",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 950,
    moveIn:         3000,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "flint-mi-3918-trumbull",
    city:  "Flint",
    state: "MI",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 895,
    moveIn:         3000,
    lockedPrice:    83000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "flint-mi-411-marengo",
    city:  "Flint",
    state: "MI",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 999,
    moveIn:         3000,
    lockedPrice:    99000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "flint-mi-5210-dupont",
    city:  "Flint",
    state: "MI",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 848,
    moveIn:         3000,
    lockedPrice:    72000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "flint-mi-834-remington",
    city:  "Flint",
    state: "MI",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 800,
    moveIn:         1800,
    lockedPrice:    79000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "highlandpark-mi-376-highland",
    city:  "Highland Park",
    state: "MI",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 1100,
    moveIn:         3000,
    lockedPrice:    105000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "saginaw-mi-1007-oakley",
    city:  "Saginaw",
    state: "MI",
    beds:  4,
    baths: 2,
    sqft:  "",
    status: "Available",

    monthlyPayment: 885,
    moveIn:         3000,
    lockedPrice:    75000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-10187-count",
    city:  "St. Louis",
    state: "MO",
    beds:  3,
    baths: 2,
    sqft:  936,
    status: "Available",

    monthlyPayment: 989.31,
    moveIn:         4000,
    lockedPrice:    99999,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-10249-earl",
    city:  "St. Louis",
    state: "MO",
    beds:  3,
    baths: 1,
    sqft:  737,
    status: "Available",

    monthlyPayment: 832.69,
    moveIn:         4000,
    lockedPrice:    89999,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-10869-spring",
    city:  "St. Louis",
    state: "MO",
    beds:  3,
    baths: 1,
    sqft:  927,
    status: "Available",

    monthlyPayment: 750,
    moveIn:         1450,
    lockedPrice:    69000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-2028-prairei",
    city:  "St. Louis",
    state: "MO",
    beds:  1,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 635,
    moveIn:         2000,
    lockedPrice:    57000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-2603-belle",
    city:  "St. Louis",
    state: "MO",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 800,
    moveIn:         2000,
    lockedPrice:    87000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-2617-hord",
    city:  "St. Louis",
    state: "MO",
    beds:  2,
    baths: 1,
    sqft:  800,
    status: "Available",

    monthlyPayment: 750,
    moveIn:         1500,
    lockedPrice:    73000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-32-connoly",
    city:  "St. Louis",
    state: "MO",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 775,
    moveIn:         2000,
    lockedPrice:    80000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-3738-sylvan",
    city:  "St. Louis",
    state: "MO",
    beds:  2,
    baths: 1,
    sqft:  1000,
    status: "Available",

    monthlyPayment: 895,
    moveIn:         2500,
    lockedPrice:    99000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-3819-kossuth",
    city:  "St. Louis",
    state: "MO",
    beds:  1,
    baths: 1.5,
    sqft:  "",
    status: "Available",

    monthlyPayment: 725,
    moveIn:         1500,
    lockedPrice:    69000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-3912-beachwood",
    city:  "St. Louis",
    state: "MO",
    beds:  4,
    baths: 2,
    sqft:  "",
    status: "Available",

    monthlyPayment: 895,
    moveIn:         1500,
    lockedPrice:    69000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-4627-maffit",
    city:  "St. Louis",
    state: "MO",
    beds:  2,
    baths: 1,
    sqft:  704,
    status: "Available",

    monthlyPayment: 775,
    moveIn:         1500,
    lockedPrice:    79000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-4719-plover",
    city:  "St. Louis",
    state: "MO",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 995,
    moveIn:         3000,
    lockedPrice:    99000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-4919-thelka",
    city:  "St. Louis",
    state: "MO",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 700,
    moveIn:         2000,
    lockedPrice:    79900,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-4931-plover",
    city:  "St. Louis",
    state: "MO",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 700,
    moveIn:         1800,
    lockedPrice:    85000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-4935-alcott",
    city:  "St. Louis",
    state: "MO",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 705,
    moveIn:         1500,
    lockedPrice:    65000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-5446-hodiamont",
    city:  "St. Louis",
    state: "MO",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 795,
    moveIn:         1500,
    lockedPrice:    83000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-5600-gatesworth",
    city:  "St. Louis",
    state: "MO",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 1095,
    moveIn:         4000,
    lockedPrice:    99000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-5619-janet",
    city:  "St. Louis",
    state: "MO",
    beds:  2,
    baths: 1,
    sqft:  931,
    status: "Available",

    monthlyPayment: 575,
    moveIn:         1000,
    lockedPrice:    44000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-5811-helen",
    city:  "St. Louis",
    state: "MO",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 950,
    moveIn:         3000,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-5851-ferris",
    city:  "St. Louis",
    state: "MO",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 875,
    moveIn:         2500,
    lockedPrice:    87000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-6069-harney",
    city:  "St. Louis",
    state: "MO",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 915,
    moveIn:         2500,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-6342-lena",
    city:  "St. Louis",
    state: "MO",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 891.76,
    moveIn:         3000,
    lockedPrice:    72500,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-6998-edison",
    city:  "St. Louis",
    state: "MO",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 995,
    moveIn:         4000,
    lockedPrice:    99000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "stlouis-mo-8116-pelham",
    city:  "St. Louis",
    state: "MO",
    beds:  4,
    baths: 2,
    sqft:  "",
    status: "Available",

    monthlyPayment: 900,
    moveIn:         2000,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "jackson-ms-1546-david",
    city:  "Jackson",
    state: "MS",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 950,
    moveIn:         2000,
    lockedPrice:    80000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "jackson-ms-3875-slayton",
    city:  "Jackson",
    state: "MS",
    beds:  3,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 875,
    moveIn:         2500,
    lockedPrice:    85000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "jackson-ms-533-stillwood",
    city:  "Jackson",
    state: "MS",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 819.48,
    moveIn:         2000,
    lockedPrice:    69000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "jackson-ms-740-valencia",
    city:  "Jackson",
    state: "MS",
    beds:  3,
    baths: 2,
    sqft:  "",
    status: "Available",

    monthlyPayment: 1098.02,
    moveIn:         2000,
    lockedPrice:    89250,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
  {
    id: "toledo-oh-329-mettler",
    city:  "Toledo",
    state: "OH",
    beds:  2,
    baths: 1,
    sqft:  "",
    status: "Available",

    monthlyPayment: 975,
    moveIn:         3000,
    lockedPrice:    89000,
    termText:       "30-year owner financing (contract for deed)",

    heroPhoto: "",
    photos:    [],
  },
];
/* ▲▲▲ EDIT ABOVE — nothing below ▲▲▲ */
